// Project 5001 - YouTube Cookie Extractor Browser Extension
// This script can be run in the browser console to extract YouTube cookies

(function() {
    'use strict';
    
    console.log('🍪 Project 5001 - YouTube Cookie Extractor');
    console.log('Extracting YouTube cookies...');
    
    // Get all YouTube cookies
    const cookies = document.cookie.split(';').map(cookie => {
        const [name, value] = cookie.trim().split('=');
        return { name, value };
    }).filter(cookie => 
        cookie.name && cookie.value && 
        (cookie.name.includes('SID') || 
         cookie.name.includes('HSID') || 
         cookie.name.includes('SSID') || 
         cookie.name.includes('APISID') || 
         cookie.name.includes('SAPISID') ||
         cookie.name.includes('__Secure') ||
         cookie.name.includes('LOGIN_INFO') ||
         cookie.name.includes('VISITOR_INFO'))
    );
    
    if (cookies.length === 0) {
        console.log('❌ No YouTube cookies found. Make sure you are logged into YouTube.');
        return;
    }
    
    console.log(`✅ Found ${cookies.length} YouTube cookies`);
    
    // Generate Netscape format cookies
    const netscapeFormat = cookies.map(cookie => {
        const domain = '.youtube.com';
        const domainSpecified = 'TRUE';
        const path = '/';
        const secure = cookie.name.startsWith('__Secure') ? 'TRUE' : 'FALSE';
        const expiry = Math.floor(Date.now() / 1000) + (365 * 24 * 60 * 60); // 1 year from now
        const name = cookie.name;
        const value = cookie.value;
        
        return `${domain}\t${domainSpecified}\t${path}\t${secure}\t${expiry}\t${name}\t${value}`;
    });
    
    // Create the full cookies file content
    const cookiesFile = [
        '# Netscape HTTP Cookie File',
        '# This file is generated by Project 5001 Cookie Extractor',
        '# Generated on: ' + new Date().toISOString(),
        '# Do not edit manually',
        '',
        ...netscapeFormat
    ].join('\n');
    
    // Create download link
    const blob = new Blob([cookiesFile], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'cookies.txt';
    a.textContent = 'Download cookies.txt';
    a.style.cssText = `
        position: fixed;
        top: 20px;
        right: 20px;
        background: #ff0000;
        color: white;
        padding: 10px 15px;
        border-radius: 5px;
        text-decoration: none;
        font-family: Arial, sans-serif;
        font-weight: bold;
        z-index: 10000;
        box-shadow: 0 2px 10px rgba(0,0,0,0.3);
    `;
    
    document.body.appendChild(a);
    
    console.log('📥 Download link created! Click the red button in the top-right corner.');
    console.log('📋 Cookie names found:', cookies.map(c => c.name).join(', '));
    
    // Also log the cookies for manual copying
    console.log('\n📋 Manual copy format:');
    console.log('# Copy these lines to cookies.txt:');
    console.log(netscapeFormat.join('\n'));
    
})(); 